version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongoDb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-net

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mongo
    container_name: node-api
    restart: unless-stopped
    env_file: ./server/.env
    volumes:
      - ./server:/app/server
    networks:
      - app-net
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - api
    container_name: react-ui
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-net
    ports:
      - "5173:5173"

networks:
  app-net:
    driver: bridge

volumes:
  mongo_data:
