global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - host.docker.internal:9090

  - job_name: "ecommerce-server"
    static_configs:
      - targets:
          - host.docker.internal:9323

  - job_name: "cAdvisor"
    static_configs:
      - targets:
          - host.docker.internal:8080
